"use client";

import { useLanguage } from "../contexts/LanguageContext";
import styles from "../app/(website)/legal.module.css";

const content = {
  privacy: {
    ar: { label: "الروابط القانونية", title: "سياسة الخصوصية", intro: "تحترم جمعية الآل والأصحاب خصوصية زوار موقعها والمستفيدين من خدماتها، وتتعامل مع بياناتهم بمسؤولية ووضوح.", sections: [["البيانات التي نجمعها", "قد نجمع الاسم وبيانات الاتصال ومحتوى الرسائل والتعليقات، والمعلومات والمستندات اللازمة لدراسة طلبات الدعم، إضافة إلى بيانات تقنية محدودة لحماية الموقع وتحسينه."], ["استخدام البيانات", "نستخدم البيانات للرد على الاستفسارات ودراسة الطلبات وإدارة التعليقات وتقديم خدمات الجمعية وتحسين تجربة المستخدم والوفاء بالمتطلبات النظامية."], ["طلبات الدعم والتعليقات", "تُعامل مستندات طلبات الدعم بسرية وتستخدم للتحقق والدراسة والتواصل. لا يُنشر بريد صاحب التعليق، ويمكن حفظ بياناته على جهازه باختياره."], ["المشاركة والحفظ", "لا نبيع البيانات الشخصية. وقد نشارك القدر الضروري مع مزودي الخدمة أو الجهات المختصة وفق متطلبات الخدمة أو النظام، ونحتفظ به للمدة اللازمة فقط."], ["الحماية وحقوقك", "نتخذ تدابير مناسبة لحماية البيانات. ويمكنك طلب الاستفسار عنها أو تصحيحها أو حذفها متى كان ذلك ممكنًا نظامًا."], ["الروابط والتواصل", "تخضع المنصات الخارجية لسياساتها الخاصة. للاستفسار تواصل عبر tawasul.aalalashab@gmail.com أو ‎+973 17774001. وقد تُحدّث هذه السياسة عند الحاجة."]] },
    en: { label: "Legal information", title: "Privacy Policy", intro: "Aal & Al Ashab Society respects the privacy of website visitors and service beneficiaries and handles their information responsibly and transparently.", sections: [["Information we collect", "We may collect your name, contact details, messages, comments, information and documents required for support applications, and limited technical data used to protect and improve the website."], ["How we use information", "We use information to answer inquiries, assess applications, manage comments, provide Society services, improve user experience, and meet legal requirements."], ["Support applications and comments", "Support documents are treated confidentially and used for verification, assessment, and communication. A commenter’s email is not published, and browser details are saved only when they choose that option."], ["Sharing and retention", "We do not sell personal data. We may share only what is necessary with service providers or competent authorities when required for a service or by law, and retain it only as long as needed."], ["Security and your rights", "We take appropriate measures to protect data. You may ask about, correct, or request deletion of your information whenever permitted by applicable law."], ["External services and contact", "External platforms follow their own policies. For privacy inquiries, contact tawasul.aalalashab@gmail.com or +973 17774001. This policy may be updated when necessary."]] },
    fa: { label: "اطلاعات حقوقی", title: "سیاست حفظ حریم خصوصی", intro: "بنیاد آل و اصحاب به حریم خصوصی بازدیدکنندگان و بهره‌مندان خدمات احترام می‌گذارد و با اطلاعات آنان مسئولانه و شفاف رفتار می‌کند.", sections: [["اطلاعات گردآوری‌شده", "ممکن است نام، اطلاعات تماس، پیام‌ها، دیدگاه‌ها، مدارک لازم برای درخواست حمایت و داده‌های فنی محدود برای حفاظت و بهبود وب‌سایت جمع‌آوری شود."], ["نحوه استفاده", "اطلاعات برای پاسخ‌گویی، بررسی درخواست‌ها، مدیریت دیدگاه‌ها، ارائه خدمات بنیاد، بهبود تجربه کاربر و رعایت الزامات قانونی استفاده می‌شود."], ["درخواست حمایت و دیدگاه‌ها", "مدارک درخواست حمایت محرمانه است و تنها برای بررسی و تماس استفاده می‌شود. ایمیل دیدگاه‌دهنده منتشر نمی‌شود و ذخیره اطلاعات در مرورگر اختیاری است."], ["اشتراک‌گذاری و نگهداری", "اطلاعات شخصی فروخته نمی‌شود. تنها مقدار ضروری ممکن است برای ارائه خدمت یا الزام قانونی با ارائه‌دهندگان خدمت یا مراجع ذی‌صلاح به اشتراک گذاشته شود."], ["امنیت و حقوق شما", "تدابیر مناسب برای حفاظت از داده‌ها اتخاذ می‌شود. در چارچوب قانون می‌توانید درباره اطلاعات خود پرس‌وجو یا اصلاح و حذف آن را درخواست کنید."], ["خدمات خارجی و تماس", "خدمات خارجی تابع سیاست‌های خود هستند. برای پرسش‌ها با tawasul.aalalashab@gmail.com یا ‎+973 17774001 تماس بگیرید. این سیاست ممکن است به‌روزرسانی شود."]] },
  },
  terms: {
    ar: { label: "الروابط القانونية", title: "الشروط والأحكام", intro: "تنظم هذه الشروط استخدام موقع جمعية الآل والأصحاب وخدماته الرقمية وتوضح حقوق المستخدم ومسؤولياته.", sections: [["قبول الشروط", "يعني استخدام الموقع موافقتك على هذه الشروط. يرجى التوقف عن استخدامه إذا لم توافق عليها."], ["طبيعة الموقع والاستخدام", "يقدم الموقع معلومات الجمعية ومحتواها وخدمات التواصل وطلبات الدعم. يجب استخدامه بصورة مشروعة، ويُحظر تعطيله أو إساءة استخدامه أو انتحال صفة الغير."], ["طلبات الدعم", "لا يعني تقديم الطلب قبوله أو استحقاق المساعدة تلقائيًا؛ فالطلبات تخضع للدراسة والتحقق وتوافر الموارد والضوابط المعتمدة لدى الجمعية."], ["المحتوى والتعليقات", "يتحمل المستخدم مسؤولية ما يرسله، وللجمعية مراجعة المحتوى المخالف أو إخفاؤه أو حذفه. ولا يمثل نشر تعليق تبني الجمعية للرأي الوارد فيه."], ["الملكية الفكرية", "تعود حقوق الموقع ومواده إلى الجمعية أو أصحاب الحقوق. يجوز مشاركة الروابط وتحميل المعلقات للاستخدام الشخصي غير التجاري مع نسبتها إلى مصدرها."], ["الخدمات الخارجية والمسؤولية", "تخضع الروابط الخارجية لشروط مشغليها. لا تضمن الجمعية خلو الموقع من الانقطاع أو الخطأ، ولا تتحمل الخسائر غير المباشرة في الحدود التي تسمح بها الأنظمة."], ["القانون والتحديث", "تُفسر الشروط وفق الأنظمة المعمول بها في مملكة البحرين، ويصبح النص المنشور نافذًا عند تحديثه. للاستفسار: tawasul.aalalashab@gmail.com."]] },
    en: { label: "Legal information", title: "Terms and Conditions", intro: "These terms govern use of Aal & Al Ashab Society’s website and digital services and explain user rights and responsibilities.", sections: [["Acceptance", "Using the website means you accept these terms. Please stop using it if you do not agree."], ["Website purpose and acceptable use", "The website provides information, content, contact services, and support applications. It must be used lawfully and may not be disrupted, misused, or used to impersonate others."], ["Support applications", "Submitting an application does not guarantee acceptance or assistance. Applications are assessed subject to verification, available resources, priorities, and the Society’s approved rules."], ["Content and comments", "Users are responsible for submitted material. The Society may review, hide, or remove content that violates law, public standards, or others’ rights. Publishing a comment does not mean the Society endorses it."], ["Intellectual property", "The website and its materials belong to the Society or their respective owners. Links may be shared and posters downloaded for personal, non-commercial use with proper attribution."], ["External services and liability", "External links are governed by their operators. The Society does not guarantee uninterrupted or error-free access and, where legally permitted, is not liable for indirect loss."], ["Applicable law and updates", "These terms are interpreted under the laws applicable in the Kingdom of Bahrain. The latest published version applies. Contact: tawasul.aalalashab@gmail.com."]] },
    fa: { label: "اطلاعات حقوقی", title: "شرایط و ضوابط", intro: "این شرایط استفاده از وب‌سایت و خدمات دیجیتال بنیاد آل و اصحاب و حقوق و مسئولیت‌های کاربران را تنظیم می‌کند.", sections: [["پذیرش شرایط", "استفاده از وب‌سایت به معنای پذیرش این شرایط است. در صورت مخالفت، استفاده را متوقف کنید."], ["ماهیت وب‌سایت و استفاده مجاز", "وب‌سایت اطلاعات، محتوا، راه‌های تماس و درخواست حمایت را ارائه می‌کند. استفاده باید قانونی باشد و اختلال، سوءاستفاده یا جعل هویت ممنوع است."], ["درخواست‌های حمایت", "ثبت درخواست به معنای پذیرش یا استحقاق خودکار نیست. درخواست‌ها بر پایه بررسی، راستی‌آزمایی، منابع موجود و ضوابط بنیاد ارزیابی می‌شوند."], ["محتوا و دیدگاه‌ها", "کاربر مسئول محتوای ارسالی است. بنیاد می‌تواند محتوای ناقض قانون، اخلاق عمومی یا حقوق دیگران را بررسی، پنهان یا حذف کند. انتشار دیدگاه به معنای تأیید آن نیست."], ["مالکیت فکری", "حقوق وب‌سایت و مطالب آن متعلق به بنیاد یا صاحبان حقوق است. اشتراک پیوندها و دریافت پوسترها برای استفاده شخصی و غیرتجاری با ذکر منبع مجاز است."], ["خدمات خارجی و مسئولیت", "پیوندهای خارجی تابع شرایط ارائه‌دهندگان خود هستند. بنیاد دسترسی بدون وقفه و خطا را تضمین نمی‌کند و در حدود قانون مسئول زیان غیرمستقیم نیست."], ["قانون و به‌روزرسانی", "این شرایط بر اساس قوانین جاری پادشاهی بحرین تفسیر می‌شود و آخرین نسخه منتشرشده معتبر است. تماس: tawasul.aalalashab@gmail.com."]] },
  },
};

export default function LegalContent({ type }) {
  const { language } = useLanguage();
  const text = content[type][language];
  return <main className={styles.page}><section className={styles.hero}><div className={styles.container}><span>{text.label}</span><h1>{text.title}</h1></div></section><section className={styles.contentSection}><div className={styles.container}><article className={styles.contentCard}><p className={styles.intro}>{text.intro}</p><div className={styles.sections}>{text.sections.map(([title, body]) => <section className={styles.section} key={title}><h2>{title}</h2><p>{body}</p></section>)}</div></article></div></section></main>;
}
