"use client";

import Image from "next/image";
import Link from "next/link";
import { FiArrowLeft, FiBarChart2, FiCalendar, FiDownload, FiFileText, FiTrendingUp } from "react-icons/fi";
import { useLanguage } from "../contexts/LanguageContext";
import styles from "../app/(website)/reports/financial/page.module.css";

const translations = {
  ar: { annual: "السنوية", financial: "المالية", releases: "إصدارات الجمعية", reports: "التقارير", annualLead: "مكتبة منظمة تجمع تقارير الجمعية السنوية وتوثق منجزاتها ومشروعاتها وأثرها خلال الأعوام المختلفة.", financialLead: "مكتبة منظمة لعرض تقارير الجمعية وتوثيق مشروعاتها ونتائجها بصورة واضحة وسهلة الوصول.", documented: "تقارير موثقة", viewDownload: "عرض وتنزيل", library: "مكتبة الجمعية", available: "تقرير متاح", availableReports: "التقارير المتاحة", libraryTitle: "مكتبة التقارير", browse: "يمكنك فتح التقرير وتصفّح صفحاته داخل الموقع أو تنزيل نسخة للاحتفاظ بها.", report: "تقرير", title: "تقرير أضاحي", description: "تقرير مصور يوثق مشروع الأضاحي وأثره، مع إمكانية تصفح جميع صفحات التقرير وتنزيل نسخة PDF.", date: "17 يناير 2025", type: "تقرير مصور", view: "عرض التقرير", open: "فتح", download: "تنزيل" },
  en: { annual: "Annual", financial: "Financial", releases: "Society publications", reports: "reports", annualLead: "An organized library documenting the Society’s annual achievements, projects, and impact.", financialLead: "An accessible library presenting the Society’s reports, projects, and results clearly.", documented: "Documented reports", viewDownload: "View and download", library: "Society library", available: "report available", availableReports: "Available reports", libraryTitle: "Reports library", browse: "Open and browse the report on the website or download a copy for later.", report: "report", title: "Adahi Report", description: "An illustrated report documenting the Adahi project and its impact, available to browse and download as PDF.", date: "17 January 2025", type: "Illustrated report", view: "View report", open: "Open", download: "Download" },
  fa: { annual: "سالانه", financial: "مالی", releases: "انتشارات بنیاد", reports: "گزارش‌های", annualLead: "کتابخانه‌ای منظم برای ثبت دستاوردها، طرح‌ها و اثر سالانه بنیاد.", financialLead: "کتابخانه‌ای روشن و در دسترس برای گزارش‌ها، طرح‌ها و نتایج بنیاد.", documented: "گزارش‌های مستند", viewDownload: "مشاهده و دریافت", library: "کتابخانه بنیاد", available: "گزارش موجود", availableReports: "گزارش‌های موجود", libraryTitle: "کتابخانه گزارش‌ها", browse: "گزارش را در وب‌سایت ورق بزنید یا نسخه‌ای برای مراجعه بعدی دریافت کنید.", report: "گزارش", title: "گزارش قربانی", description: "گزارشی تصویری از طرح قربانی و اثر آن، با امکان مرور همه صفحات و دریافت PDF.", date: "۱۷ ژانویه ۲۰۲۵", type: "گزارش تصویری", view: "مشاهده گزارش", open: "باز کردن", download: "دریافت" },
};

export default function LocalizedReportsPage({ type }) {
  const { language } = useLanguage();
  const text = translations[language];
  const isAnnual = type === "annual";
  const Icon = isAnnual ? FiTrendingUp : FiBarChart2;
  const kind = isAnnual ? text.annual : text.financial;
  return <main className={styles.page}><section className={styles.hero}><div className={styles.heroOverlay} /><div className={styles.heroPattern} aria-hidden /><div className={`${styles.container} ${styles.heroGrid}`}><div className={styles.heroContent}><span className={styles.eyebrow}><Icon aria-hidden />{text.releases}</span><h1>{text.reports} <span>{kind}</span></h1><p>{isAnnual ? text.annualLead : text.financialLead}</p><div className={styles.heroFeatures}><span><FiFileText />{text.documented}</span><span><FiDownload />{text.viewDownload}</span></div></div><div className={styles.heroVisual} aria-hidden><div className={styles.visualGlow} /><div className={styles.visualCardBack} /><div className={styles.visualCard}><div className={styles.visualTop}><span><Icon /></span><small>{text.library}</small></div><div className={styles.visualCount}>01</div><strong>{text.available}</strong><div className={styles.visualBars}><i /><i /><i /><i /></div><div className={styles.visualFooter}><span>{kind}</span><FiFileText /></div></div></div></div></section><section className={styles.reportsSection}><div className={styles.container}><header className={styles.sectionHeader}><div><span>{text.availableReports}</span><h2>{text.libraryTitle}</h2><p>{text.browse}</p></div><span className={styles.count}>01 {text.report}</span></header><div className={styles.reportsGrid}><article className={styles.reportCard}><Link href="/reports/adahi" className={styles.imageWrap} aria-label={`${text.open} ${text.title}`}><Image src="/aladha.jpg" alt={text.title} fill sizes="(max-width: 640px) 100vw, 33vw" className={styles.cardImage} /><span className={styles.typeBadge}><FiFileText />{text.type}</span><span className={styles.reportNumber}>01</span></Link><div className={styles.cardBody}><div className={styles.date}><FiCalendar />{text.date}</div><h3><Link href="/reports/adahi">{text.title}</Link></h3><p>{text.description}</p><div className={styles.cardActions}><Link href="/reports/adahi" className={styles.viewButton}>{text.view}<FiArrowLeft /></Link><a href="/adahi-report-1444.pdf" download className={styles.downloadButton} aria-label={`${text.download} ${text.title}`}><FiDownload /></a></div></div></article></div></div></section></main>;
}
