"use client";

import Image from "next/image";
import { useSearchParams } from "next/navigation";
import { FiBookOpen, FiCheckCircle, FiHeart, FiMail, FiMapPin, FiPhone, FiUser, FiUsers } from "react-icons/fi";
import HeroSection from "./HeroSection";
import styles from "../app/(website)/about/page.module.css";

const translations = {
  ar: {
    hero: "من نحن",
    aboutKicker: "منذ عام 2006", aboutTitle: "نبذة عن الجمعية", aboutText: "تأسست الجمعية في مملكة البحرين بقرار من وزارة التنمية الاجتماعية رقم (32) لسنة 2006م؛ وقد تم إشهارها وتسجيلها بموجب قرار وزيرة التنمية الاجتماعية تحت رقم 25/ج/أح.ح باسم (جمعية الآل والأصحاب).",
    goalsKicker: "ما نسعى إليه", goalsTitle: "أهداف الجمعية", goalsIntro: "تسعى الجمعية لتحقيق جملة من الأهداف وإنجاز عدد من الرؤى من خلال عملها ومسيرتها الدعوية؛ وتتلخص مساعي الجمعية في هذا الشأن فيما يلي:", goals: ["نشر تراث الآل (آل البيت) الأطهار، والأصحاب (الصحابة) الأخيار، بما يليق بمكانتهم العظيمة عند المسلمين.", "العمل على إبراز العلاقات الأخوية الحميمة بين الآل والأصحاب، وغرس محبتهم في نفوس المسلمين.", "إظهار دور الآل والأصحاب في خدمة الإسلام، من خلال تمسكهم بالقرآن الكريم والسنة النبوية.", "تعزيز مفهوم التلاحم بين أفراد المجتمع الواحد من خلال تجلية المفاهيم الخاطئة في نفوس بعض المسلمين بشأن الآل (آل البيت) الأطهار والأصحاب (الصحابة) الأخيار."],
    chairmanKicker: "من القلب", chairmanTitle: "كلمة رئيس مجلس الإدارة", chairman: ["الحمد لله وكفى، والصلاة والسلام على النبي المصطفى، وعلى آله وصحبه وسلم، أما بعد:", "يقول الله عز وجل: {هُوَ الَّذِي أَنزَلَ عَلَيْكَ الْكِتَابَ مِنْهُ آيَاتٌ مُّحْكَمَاتٌ هُنَّ أُمُّ الْكِتَابِ وَأُخَرُ مُتَشَابِهَاتٌ ۖ فَأَمَّا الَّذِينَ فِي قُلُوبِهِمْ زَيْغٌ فَيَتَّبِعُونَ مَا تَشَابَهَ مِنْهُ ابْتِغَاءَ الْفِتْنَةِ وَابْتِغَاءَ تَأْوِيلِهِ ۗ وَمَا يَعْلَمُ تَأْوِيلَهُ إِلَّا اللَّهُ ۗ وَالرَّاسِخُونَ فِي الْعِلْمِ يَقُولُونَ آمَنَّا بِهِ كُلٌّ مِّنْ عِندِ رَبِّنَا ۗ وَمَا يَذَّكَّرُ إِلَّا أُولُ الْأَلْبَابِ} [آل عمران: 7].", "من يستقرئ التاريخ الإسلامي ويسبر أغوار حوادثه، يتبين له جليًا الكم الهائل من الموضوعات في الأحاديث والآثار التي تطلع أصحابها من خلالها إلى خلق أرضية خصبة لنشر عقائدهم التي ما أنزل الله بها من سلطان. وكانت جل هذه الموضوعات تصب في الطعن في الرعيل الأول من أصحاب رسول الله صلى الله عليه وآله وسلم وآل بيته رضي الله عنهم.", "فأما كتاب الله، فقد عمدوا إلى تأويل آياته وصرفها عن ظاهرها. وأما السنة، فما أسهل أن يضعوا لأنفسهم حديثًا؛ حتى قال أحدهم وقد تاب: كنا إذا هوينا أمرًا صيرناه حديثًا.", "وفي خضم تلك الحوادث مرت على الأمة الإسلامية دول عديدة، انتصر بعضها لمذهب الدولة؛ فكان من المخالفين لهم أن كتموا فضائل من ليس على مذهب الدولة، من آل وأصحاب.", "ولكن يشاء الله أن يخرج من بين خوف هؤلاء وحسد أولئك ما يملأ المشرق والمغرب من روايات ونصوص وحوادث وعبر، تخالف مقاصد أولئك القوم ونياتهم.", "وجمعية الآل والأصحاب، وقد هالها حجم هذا التراث النقي الصافي بين ركام هذه الموضوعات، قد آلت على نفسها أن تُخرج للنور ما وقفت عليه من روايات ونصوص وشواهد تعكس نقاء ذلك الجيل المثالي، الذي قال فيهم الله عز وجل: {كُنتُمْ خَيْرَ أُمَّةٍ أُخْرِجَتْ لِلنَّاسِ تَأْمُرُونَ بِالْمَعْرُوفِ وَتَنْهَوْنَ عَنِ الْمُنْكَرِ وَتُؤْمِنُونَ بِاللَّهِ} [آل عمران: 110]؛ وكيف أن ما روجه أعداؤهم إنما هو نتاج خيال مريض، من أناس اشتروا لذة الدنيا بثواب الآخرة.", "وفي الأسطر اللاحقة موجز عام يُعرّف بالجمعية وأهدافها وإنجازاتها منذ أول نشأتها، نضعه بين أيديكم ثقة منا بضرورة إطلاعكم على نتاج إسهاماتكم المادية والمعنوية ودعمكم المستمر لنا.", "وصلى الله على نبينا محمد، وعلى آله وصحبه وسلم، وآخر دعوانا أن الحمد لله رب العالمين."], chairmanRole: "رئيس مجلس الإدارة", chairmanName: "عبد الناصر حسن أبو سيف",
    vision: "رؤيتنا", visionText: "حب آل النبي محمد صلى الله عليه وسلم وأصحابه رضي الله عنهم هو من نفس محبة الرسول صلى الله عليه وسلم.", mission: "رسالتنا", missionText: "نسعى لتصحيح المفاهيم المرتبطة بالعلاقة بين الآل (آل بيت النبوة) الأطهار، والأصحاب (الصحابة) الأخيار.",
    boardKicker: "قيادة الجمعية", boardTitle: "أعضاء مجلس الإدارة", board: [["عبد الناصر حسن أبو سيف", "رئيس مجلس الإدارة"], ["محمد علي علي الفرج", "نائب رئيس مجلس الإدارة"], ["السيد هاني محي الدين", "أمين السر"], ["السيد إبراهيم محي الدين", "الأمين المالي"], ["فاروق إسماعيل العوضي", "رئيس اللجنة الاجتماعية"], ["فتحي عبدالله الدوسري", "رئيس اللجنة الثقافية"], ["صلاح حيدر حسين", "عضو"]],
    effortsKicker: "علم وعطاء", effortsTitle: "جهود الجمعية في الدعوة", efforts: ["كفالة طلاب العلم.", "كفالة الباحثين وتفريغهم للبحث والتأليف.", "طباعة الكتب المتعلقة بإحياء تراث الآل والأصحاب.", "الدورات العلمية: تعقد الجمعية كثيرًا من الدورات التي تتسم بالطابع العلمي التأصيلي.", "المحاضرات: تقوم الجمعية بإقامة العديد من المحاضرات والندوات.", "المساهمة في تخفيف الأعباء المعيشية عن الأسر الفقيرة والأيتام."],
    impactTitle: "أثر الجمعية في المجتمع", impactIntro: "والذي يطلع على نشاطات الجمعية ووسائلها وأهدافها التي تسعى لتحقيقها، يتضح له الآتي:", impact: ["أن الجمعية قد أخذت على عاتقها تعزيز التلاحم الوطني من خلال تصحيح المفاهيم الخاطئة عند البعض بشأن علاقة آل البيت الأطهار والصحابة الأخيار، والذود عن عرض الصحابة الكرام، واتخاذهم قدوات ونماذج صالحة لكل المسلمين. وقد شمل نشاطها الجوانب التعليمية والاجتماعية والثقافية بما يغطي أوجه الحياة المختلفة في المجتمع.", "كان للجمعية دور بارز وجهد كبير في مقاومة الفكر الهدام الذي يروج لمفاهيم خاطئة عن تراث الآل والأصحاب، من خلال التوعية بآثاره وبيان مخاطره ومعالجة إفرازاته المختلفة، وتوسيع النشاط الثقافي والاجتماعي في المجتمع.", "أخذت الجمعية حيزًا كبيرًا في الساحة الثقافية من خلال كثرة منتسبيها والمستفيدين من خدماتها والمنتفعين من نشاطها، مما منحها وزنًا اجتماعيًا وحضورًا في الساحة البحرينية عمومًا."],
    contactKicker: "بيانات الجمعية", contactTitle: "تواصل معنا", addressLabel: "العنوان", address: "مملكة البحرين - الرفاع الشرقي (الحجيات) - مجمع: 929 - طريق: 2914 - مبنى: 686أ", mailbox: "صندوق البريد", phone: "رقم الهاتف", email: "البريد الإلكتروني",
  },
  en: {
    hero: "About Us", aboutKicker: "Since 2006", aboutTitle: "About the Society", aboutText: "The Society was established in the Kingdom of Bahrain under Ministry of Social Development Resolution No. 32 of 2006 and was officially declared and registered under Ministerial Resolution No. 25/J/AH.H as Aal & Al Ashab Society.",
    goalsKicker: "What we pursue", goalsTitle: "Society Goals", goalsIntro: "Through its educational and outreach journey, the Society seeks to achieve a set of goals and visions, summarized as follows:", goals: ["Publishing the heritage of the noble Ahl al-Bayt and the honorable Companions in a manner worthy of their great standing among Muslims.", "Highlighting the close bonds of brotherhood between Ahl al-Bayt and the Companions and nurturing love for them in Muslim hearts.", "Demonstrating their role in serving Islam through adherence to the Holy Quran and the Prophetic Sunnah.", "Strengthening cohesion within society by correcting misconceptions about the noble Ahl al-Bayt and the honorable Companions."],
    chairmanKicker: "From the heart", chairmanTitle: "Chairman’s Message", chairman: ["Praise be to Allah, and peace and blessings be upon the chosen Prophet, his family, and his Companions.", "Allah Almighty says: “It is He who has sent down to you the Book; in it are verses precise—they are the foundation of the Book—and others unspecific...” [Aal Imran: 7].", "A careful reading of Islamic history reveals the large body of fabricated reports created to spread unsupported beliefs, many of which sought to discredit the first generation of the Messenger’s Companions and his household, may Allah be pleased with them.", "Some distorted the apparent meaning of Quranic verses, while others fabricated reports to support their inclinations. During different historical periods, political and sectarian loyalties also led some to conceal the virtues of those outside the prevailing position.", "Yet Allah willed that, despite fear and envy, abundant narrations, texts, events, and lessons would spread across the East and West, contradicting those intentions.", "Confronted by the scale of this pure heritage amid layers of fabrication, Aal & Al Ashab Society committed itself to bringing to light reliable narrations, texts, and evidence reflecting the integrity of that exemplary generation described by Allah: “You are the best nation produced for mankind...” [Aal Imran: 110].", "The following sections offer an overview of the Society, its goals, and achievements since its establishment. We present them so that you may see the fruit of your material and moral contributions and your continued support.", "May Allah’s peace and blessings be upon our Prophet Muhammad, his family, and his Companions. Praise be to Allah, Lord of the worlds."], chairmanRole: "Chairman of the Board", chairmanName: "Abdulnaser Hassan Abu Saif",
    vision: "Our Vision", visionText: "Love for the family of Prophet Muhammad and his Companions is inseparable from love for the Messenger himself.", mission: "Our Mission", missionText: "We seek to correct misconceptions concerning the relationship between the noble family of the Prophet and his honorable Companions.",
    boardKicker: "Society leadership", boardTitle: "Board Members", board: [["Abdulnaser Hassan Abu Saif", "Chairman"], ["Mohammed Ali Ali Al Faraj", "Vice Chairman"], ["Sayed Hani Mohieddin", "Secretary"], ["Sayed Ibrahim Mohieddin", "Treasurer"], ["Farooq Ismail Al Awadhi", "Head of the Social Committee"], ["Fathi Abdullah Al Dosari", "Head of the Cultural Committee"], ["Salah Haider Hussain", "Member"]],
    effortsKicker: "Knowledge and giving", effortsTitle: "The Society’s Outreach Efforts", efforts: ["Sponsoring students of knowledge.", "Supporting researchers and enabling them to focus on research and writing.", "Printing books that revive the heritage of Ahl al-Bayt and the Companions.", "Holding academically grounded educational courses.", "Organizing lectures and seminars.", "Helping ease the living burdens of low-income families and orphans."],
    impactTitle: "Our Community Impact", impactIntro: "A review of the Society’s activities, methods, and goals demonstrates the following:", impact: ["The Society strengthens national cohesion by correcting misconceptions about the relationship between Ahl al-Bayt and the Companions, defending their honor, and presenting them as positive models. Its educational, social, and cultural work covers diverse aspects of community life.", "The Society plays a prominent role in confronting destructive ideas and false claims about their heritage through awareness, explaining risks, addressing their effects, and expanding cultural and social activity.", "Through its members, beneficiaries, and wide-ranging services, the Society has built a significant cultural and social presence in Bahrain."],
    contactKicker: "Society details", contactTitle: "Contact Us", addressLabel: "Address", address: "Kingdom of Bahrain — East Riffa (Al Hajiyat), Block 929, Road 2914, Building 686A", mailbox: "P.O. Box", phone: "Phone", email: "Email",
  },
  fa: {
    hero: "درباره ما", aboutKicker: "از سال 2006", aboutTitle: "درباره بنیاد", aboutText: "بنیاد در پادشاهی بحرین بر پایه مصوبه شماره 32 وزارت توسعه اجتماعی در سال 2006 تأسیس و بر اساس مصوبه وزیر توسعه اجتماعی به شماره 25/ج/أح.ح با نام بنیاد آل و اصحاب ثبت و اعلام رسمی شد.",
    goalsKicker: "آنچه دنبال می‌کنیم", goalsTitle: "اهداف بنیاد", goalsIntro: "بنیاد در مسیر علمی و فرهنگی خود مجموعه‌ای از اهداف و چشم‌اندازها را دنبال می‌کند:", goals: ["انتشار میراث پاک اهل‌بیت و اصحاب نیک، به شیوه‌ای شایسته جایگاه والای آنان نزد مسلمانان.", "نمایان ساختن روابط صمیمانه و برادرانه میان اهل‌بیت و اصحاب و نهادینه کردن محبت آنان در دل مسلمانان.", "نشان دادن نقش اهل‌بیت و اصحاب در خدمت به اسلام از طریق پایبندی آنان به قرآن و سنت پیامبر.", "تقویت همبستگی جامعه با اصلاح برداشت‌های نادرست درباره اهل‌بیت پاک و اصحاب گرامی."],
    chairmanKicker: "از دل", chairmanTitle: "پیام رئیس هیئت‌مدیره", chairman: ["ستایش خداوند را و درود و سلام بر پیامبر برگزیده، خاندان و اصحاب او.", "خداوند متعال در آیه 7 سوره آل عمران می‌فرماید که در کتاب، آیاتی محکم و آیاتی متشابه است و راسخان در دانش به همه آن ایمان دارند.", "بررسی تاریخ اسلام حجم فراوانی از روایت‌های ساختگی را آشکار می‌کند که برای گسترش باورهای بی‌اساس پدید آمدند و بسیاری از آن‌ها نسل نخست اصحاب پیامبر و اهل‌بیت ایشان را هدف قرار دادند.", "برخی آیات را از معنای روشن خود دور کردند و برخی روایت‌هایی برای خواسته‌های خود ساختند. در دوره‌های تاریخی گوناگون نیز تعصب سیاسی یا مذهبی باعث پنهان ماندن فضایل مخالفان شد.", "با این همه، خداوند اراده کرد روایت‌ها، متون، رویدادها و عبرت‌های فراوانی در شرق و غرب منتشر شود که آن اهداف نادرست را آشکار می‌سازد.", "بنیاد آل و اصحاب در برابر این میراث پاک در میان انبوه مطالب ساختگی، متعهد شد روایت‌ها، متون و شواهد معتبر درباره پاکی آن نسل نمونه را آشکار سازد؛ نسلی که خداوند در آیه 110 آل عمران آن را بهترین امت معرفی کرده است.", "بخش‌های بعدی معرفی کوتاهی از بنیاد، اهداف و دستاوردهای آن از آغاز تأسیس است تا نتیجه کمک‌های مادی و معنوی و پشتیبانی پیوسته شما روشن شود.", "درود خدا بر پیامبر ما محمد، خاندان و اصحاب او، و ستایش مخصوص پروردگار جهانیان است."], chairmanRole: "رئیس هیئت‌مدیره", chairmanName: "عبدالناصر حسن ابوسیف",
    vision: "چشم‌انداز ما", visionText: "محبت خاندان پیامبر محمد و اصحاب ایشان از همان محبت رسول خدا سرچشمه می‌گیرد.", mission: "رسالت ما", missionText: "برای اصلاح برداشت‌های مرتبط با رابطه میان خاندان پاک پیامبر و اصحاب نیک ایشان تلاش می‌کنیم.",
    boardKicker: "مدیریت بنیاد", boardTitle: "اعضای هیئت‌مدیره", board: [["عبدالناصر حسن ابوسیف", "رئیس هیئت‌مدیره"], ["محمد علی علی الفرج", "نایب‌رئیس"], ["سید هانی محی‌الدین", "دبیر"], ["سید ابراهیم محی‌الدین", "خزانه‌دار"], ["فاروق اسماعیل العوضی", "رئیس کمیته اجتماعی"], ["فتحی عبدالله الدوسری", "رئیس کمیته فرهنگی"], ["صلاح حیدر حسین", "عضو"]],
    effortsKicker: "دانش و بخشش", effortsTitle: "تلاش‌های فرهنگی بنیاد", efforts: ["حمایت از دانش‌پژوهان.", "حمایت از پژوهشگران و فراهم کردن فرصت تحقیق و تألیف.", "چاپ کتاب‌های مرتبط با احیای میراث اهل‌بیت و اصحاب.", "برگزاری دوره‌های علمی با رویکرد بنیادی.", "برگزاری سخنرانی‌ها و نشست‌ها.", "کمک به کاهش مشکلات معیشتی خانواده‌های نیازمند و یتیمان."],
    impactTitle: "اثر بنیاد در جامعه", impactIntro: "نگاهی به فعالیت‌ها، ابزارها و اهداف بنیاد نکات زیر را روشن می‌سازد:", impact: ["بنیاد با اصلاح برداشت‌های نادرست درباره رابطه اهل‌بیت و اصحاب، دفاع از جایگاه آنان و معرفی‌شان به عنوان الگو، همبستگی ملی را تقویت می‌کند. فعالیت‌های آموزشی، اجتماعی و فرهنگی آن جنبه‌های گوناگون زندگی جامعه را پوشش می‌دهد.", "بنیاد با آگاهی‌بخشی، توضیح خطرات اندیشه‌های مخرب، درمان پیامدهای آن و گسترش فعالیت فرهنگی و اجتماعی، نقشی برجسته در مقابله با ادعاهای نادرست درباره میراث اهل‌بیت و اصحاب دارد.", "تعداد اعضا، بهره‌مندان و گستره خدمات، جایگاه فرهنگی و اجتماعی قابل توجهی برای بنیاد در بحرین ایجاد کرده است."],
    contactKicker: "اطلاعات بنیاد", contactTitle: "تماس با ما", addressLabel: "نشانی", address: "پادشاهی بحرین — الرفاع شرقی (الحجیات)، مجتمع 929، خیابان 2914، ساختمان 686A", mailbox: "صندوق پستی", phone: "تلفن", email: "ایمیل",
  },
};

export default function LocalizedAbout() {
  const searchParams = useSearchParams();
  const requestedLanguage = searchParams.get("lang");
  const language = Object.hasOwn(translations, requestedLanguage) ? requestedLanguage : "ar";
  const text = translations[language];
  return (
    <main className={styles.main} lang={language} dir={language === "en" ? "ltr" : "rtl"}>
      <HeroSection title={text.hero} imageSrc="/aal-alashab-hero.webp" imageAlt={text.hero} align="center" />

      <section className={styles.aboutSection}><div className={`${styles.container} ${styles.aboutGrid}`}><div className={styles.aboutImage}><Image src="/about1.jpg" alt={text.aboutTitle} fill priority sizes="(max-width: 760px) 100vw, 48vw" /><span>2006</span></div><div className={styles.aboutCopy}><span className={styles.eyebrow}>{text.aboutKicker}</span><h2>{text.aboutTitle}</h2><p>{text.aboutText}</p></div></div></section>

      <section className={styles.goalsSection}><div className={styles.container}><header className={styles.sectionHeader}><span className={styles.eyebrow}>{text.goalsKicker}</span><h2>{text.goalsTitle}</h2><p>{text.goalsIntro}</p></header><div className={styles.goalsGrid}>{text.goals.map((goal, index) => <article key={goal}><span>{String(index + 1).padStart(2, "0")}</span><FiCheckCircle aria-hidden /><p>{goal}</p></article>)}</div></div></section>

      <section className={styles.chairmanSection}><div className={styles.container}><div className={styles.chairmanHeader}><span className={styles.quoteMark} aria-hidden>“</span><div><span className={styles.eyebrow}>{text.chairmanKicker}</span><h2>{text.chairmanTitle}</h2></div></div><article className={styles.letter}>{text.chairman.map((paragraph, index) => <p className={index === 1 ? styles.verse : ""} key={paragraph}>{paragraph}</p>)}<footer><span><FiUser aria-hidden /></span><div><small>{text.chairmanRole}</small><strong>{text.chairmanName}</strong></div></footer></article></div></section>

      <section className={styles.identitySection}><div className={`${styles.container} ${styles.identityGrid}`}><article><FiHeart aria-hidden /><span>{text.vision}</span><p>{text.visionText}</p></article><article><FiBookOpen aria-hidden /><span>{text.mission}</span><p>{text.missionText}</p></article></div></section>

      <section className={styles.boardSection}><div className={styles.container}><header className={styles.sectionHeader}><span className={styles.eyebrow}>{text.boardKicker}</span><h2>{text.boardTitle}</h2></header><div className={styles.boardVisual}><div className={styles.boardImage}><Image src="/about2.jpeg" alt={text.boardTitle} fill sizes="(max-width: 850px) 100vw, 42vw" /></div><div className={styles.members}>{text.board.map(([name, role], index) => <article key={name}><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{name}</strong><small>{role}</small></div></article>)}</div></div></div></section>

      <section className={styles.effortsSection}><div className={styles.container}><header className={styles.sectionHeader}><span className={styles.eyebrow}>{text.effortsKicker}</span><h2>{text.effortsTitle}</h2></header><div className={styles.effortsGrid}>{text.efforts.map((effort, index) => <article key={effort}><span>{index % 2 ? <FiUsers /> : <FiBookOpen />}</span><p>{effort}</p></article>)}</div></div></section>

      <section className={styles.impactSection}><div className={styles.container}><header><h2>{text.impactTitle}</h2><p>{text.impactIntro}</p></header><div className={styles.impactList}>{text.impact.map((item, index) => <article key={item}><strong>{String(index + 1).padStart(2, "0")}</strong><p>{item}</p></article>)}</div></div></section>

      <section className={styles.contactSection}><div className={styles.container}><header className={styles.sectionHeader}><span className={styles.eyebrow}>{text.contactKicker}</span><h2>{text.contactTitle}</h2></header><div className={styles.contactGrid}><a href="https://maps.google.com/?q=26.0978,50.5551" target="_blank" rel="noopener noreferrer"><FiMapPin /><span><small>{text.addressLabel}</small><strong>{text.address}</strong></span></a><div><FiBookOpen /><span><small>{text.mailbox}</small><strong dir="ltr">39104</strong></span></div><a href="tel:+97317774001"><FiPhone /><span><small>{text.phone}</small><strong dir="ltr">+973 17774001</strong></span></a><a href="mailto:tawasul.aalalashab@gmail.com"><FiMail /><span><small>{text.email}</small><strong dir="ltr">tawasul.aalalashab@gmail.com</strong></span></a></div></div></section>
    </main>
  );
}
