import { z } from "zod";

const displayLabel = z.string().trim().min(1).max(80);
const optionalDisplayLabel = z.preprocess(
  (value) => (value === "" ? undefined : value),
  displayLabel.optional(),
);
const publicAssetPath = z
  .string()
  .trim()
  .regex(/^\/[A-Za-z0-9/_-]+\.(?:svg|png|webp|avif)$/);
const phoneNumber = z
  .string()
  .trim()
  .regex(/^\d{8,15}$/);

const clientEnvironmentSchema = z.object({
  NEXT_PUBLIC_APP_NAME: z.string().trim().min(1).default("CMS Dashboard"),
  NEXT_PUBLIC_APP_SHORT_NAME: displayLabel.default("CMS"),
  NEXT_PUBLIC_APP_DESCRIPTION: z
    .string()
    .trim()
    .min(1)
    .max(180)
    .default("Reusable CMS dashboard infrastructure."),
  NEXT_PUBLIC_APP_VERSION: z.string().trim().min(1).default("1.0.0"),
  NEXT_PUBLIC_APP_LANGUAGE: z.enum(["ar", "en"]).default("ar"),
  NEXT_PUBLIC_APP_DIRECTION: z.enum(["rtl", "ltr"]).default("rtl"),
  NEXT_PUBLIC_BRAND_LOGO: publicAssetPath.default("/branding/logo.svg"),
  NEXT_PUBLIC_BRAND_DARK_LOGO: publicAssetPath.default(
    "/branding/logo-dark.svg",
  ),
  NEXT_PUBLIC_BRAND_MARK: publicAssetPath.default(
    "/branding/dashboard-mark.svg",
  ),
  NEXT_PUBLIC_LOGIN_SHOWCASE_TITLE: displayLabel.default(
    "لوحة تحكم وإدارة موقع جمعية مبتكرون",
  ),
  NEXT_PUBLIC_LOGIN_SHOWCASE_LOGO: publicAssetPath.default("/logo.png"),
  NEXT_PUBLIC_FONT_PRESET: z
    .enum(["cairo-montserrat", "cairo", "montserrat"])
    .default("cairo-montserrat"),
  NEXT_PUBLIC_SUPPORT_PHONE: phoneNumber.default("015558558579"),
  NEXT_PUBLIC_SUPPORT_WHATSAPP: phoneNumber.default("2015558558579"),
  NEXT_PUBLIC_NAV_DASHBOARD: displayLabel.default("لوحة التحكم"),
  NEXT_PUBLIC_NAV_ACCOUNT: displayLabel.default("إدارة الحساب"),
  NEXT_PUBLIC_DASHBOARD_MODULE_ARTICLES_LABEL: optionalDisplayLabel,
  NEXT_PUBLIC_DASHBOARD_MODULE_LIBRARY_LABEL: optionalDisplayLabel,
  NEXT_PUBLIC_DASHBOARD_MODULE_DISSERTATIONS_LABEL: optionalDisplayLabel,
  NEXT_PUBLIC_DASHBOARD_MODULE_LISTENING_LABEL: optionalDisplayLabel,
  NEXT_PUBLIC_DASHBOARD_MODULE_HADITH_CARDS_LABEL: optionalDisplayLabel,
  NEXT_PUBLIC_DASHBOARD_MODULE_SCIENTIFIC_FATWAS_LABEL: optionalDisplayLabel,
  NEXT_PUBLIC_DASHBOARD_MODULE_SCIENTIFIC_VIDEOS_LABEL: optionalDisplayLabel,
  NEXT_PUBLIC_DASHBOARD_MODULE_LIBRARY_INDEXES_LABEL: optionalDisplayLabel,
  NEXT_PUBLIC_DASHBOARD_MODULE_COMMENTS_LABEL: optionalDisplayLabel,
  NEXT_PUBLIC_NAV_SECTIONS: displayLabel.default("إدارة الأقسام"),
  NEXT_PUBLIC_ENTITY_SECTION_SINGULAR: displayLabel.default("القسم"),
  NEXT_PUBLIC_ENTITY_SECTION_PLURAL: displayLabel.default("الأقسام"),
  NEXT_PUBLIC_NAV_ARTICLES: displayLabel.default("إدارة المقالات"),
  NEXT_PUBLIC_ENTITY_ARTICLE_SINGULAR: displayLabel.default("المقال"),
  NEXT_PUBLIC_ENTITY_ARTICLE_PLURAL: displayLabel.default("المقالات"),
  NEXT_PUBLIC_NAV_BOOKS: displayLabel.default("إدارة الكتب"),
  NEXT_PUBLIC_ENTITY_BOOK_SINGULAR: displayLabel.default("الكتاب"),
  NEXT_PUBLIC_ENTITY_BOOK_PLURAL: displayLabel.default("الكتب"),
  NEXT_PUBLIC_ENTITY_BOOK_SERIES_SINGULAR: displayLabel.default("السلسلة"),
  NEXT_PUBLIC_ENTITY_BOOK_SERIES_PLURAL: displayLabel.default("السلاسل"),
  NEXT_PUBLIC_NAV_VISUALS: displayLabel.default("إدارة المرئيات"),
  NEXT_PUBLIC_ENTITY_VISUAL_SINGULAR: displayLabel.default("المرئية"),
  NEXT_PUBLIC_ENTITY_VISUAL_PLURAL: displayLabel.default("المرئيات"),
  NEXT_PUBLIC_NAV_GALLERY: displayLabel.default("إدارة معرض الوسائط"),
  NEXT_PUBLIC_ENTITY_MEDIA_SINGULAR: displayLabel.default("الوسيط"),
  NEXT_PUBLIC_ENTITY_MEDIA_PLURAL: displayLabel.default("الوسائط"),
  NEXT_PUBLIC_NAV_SUPERVISORS: displayLabel.default("إدارة المشرفين"),
  NEXT_PUBLIC_ENTITY_SUPERVISOR_SINGULAR: displayLabel.default("المشرف"),
  NEXT_PUBLIC_ENTITY_SUPERVISOR_PLURAL: displayLabel.default("المشرفون"),
  NEXT_PUBLIC_NAV_REPORTS: displayLabel.default("التقارير والتحليلات"),
  NEXT_PUBLIC_ENTITY_REPORT_SINGULAR: displayLabel.default("التقرير"),
  NEXT_PUBLIC_ENTITY_REPORT_PLURAL: displayLabel.default("التقارير"),
  NEXT_PUBLIC_NAV_SETTINGS: displayLabel.default("إدارة الإعدادات"),
  NEXT_PUBLIC_ENTITY_SETTING_SINGULAR: displayLabel.default("الإعداد"),
  NEXT_PUBLIC_ENTITY_SETTING_PLURAL: displayLabel.default("الإعدادات"),
  NEXT_PUBLIC_PAGE_SECTIONS_CREATE_TITLE:
    optionalDisplayLabel.default("إضافة قسم"),
  NEXT_PUBLIC_PAGE_SECTIONS_EDIT_TITLE: optionalDisplayLabel,
  NEXT_PUBLIC_PAGE_SECTIONS_DETAIL_TITLE: optionalDisplayLabel,
  NEXT_PUBLIC_PAGE_ARTICLES_CREATE_TITLE:
    optionalDisplayLabel.default("إضافة مقال"),
  NEXT_PUBLIC_PAGE_ARTICLES_EDIT_TITLE: optionalDisplayLabel,
  NEXT_PUBLIC_PAGE_ARTICLES_DETAIL_TITLE: optionalDisplayLabel,
  NEXT_PUBLIC_PAGE_BOOKS_CREATE_TITLE:
    optionalDisplayLabel.default("إضافة كتاب"),
  NEXT_PUBLIC_PAGE_BOOKS_EDIT_TITLE: optionalDisplayLabel,
  NEXT_PUBLIC_PAGE_BOOKS_DETAIL_TITLE: optionalDisplayLabel,
  NEXT_PUBLIC_PAGE_VISUALS_CREATE_TITLE:
    optionalDisplayLabel.default("إضافة مرئية"),
  NEXT_PUBLIC_PAGE_VISUALS_EDIT_TITLE: optionalDisplayLabel,
  NEXT_PUBLIC_PAGE_VISUALS_DETAIL_TITLE: optionalDisplayLabel,
  NEXT_PUBLIC_PAGE_GALLERY_CREATE_TITLE:
    optionalDisplayLabel.default("إضافة وسائط"),
  NEXT_PUBLIC_PAGE_GALLERY_EDIT_TITLE: optionalDisplayLabel,
  NEXT_PUBLIC_PAGE_GALLERY_DETAIL_TITLE: optionalDisplayLabel,
  NEXT_PUBLIC_PAGE_SUPERVISORS_CREATE_TITLE:
    optionalDisplayLabel.default("إضافة مشرف"),
  NEXT_PUBLIC_PAGE_SUPERVISORS_EDIT_TITLE: optionalDisplayLabel,
  NEXT_PUBLIC_PAGE_SUPERVISORS_DETAIL_TITLE: optionalDisplayLabel,
  NEXT_PUBLIC_PAGE_SETTINGS_CREATE_TITLE:
    optionalDisplayLabel.default("إضافة إعداد"),
  NEXT_PUBLIC_PAGE_SETTINGS_EDIT_TITLE: optionalDisplayLabel,
  NEXT_PUBLIC_PAGE_SETTINGS_DETAIL_TITLE: optionalDisplayLabel,
});

export type ClientEnvironment = z.infer<typeof clientEnvironmentSchema>;

export function validateClientEnvironment(
  environment: Record<string, string | undefined>,
): ClientEnvironment {
  const result = clientEnvironmentSchema.safeParse(environment);

  if (!result.success) {
    const issues = result.error.issues
      .map((issue) => `- ${issue.path.join(".")}: ${issue.message}`)
      .join("\n");

    throw new Error(`Invalid client environment configuration:\n${issues}`);
  }

  return result.data;
}

export const clientEnv = validateClientEnvironment({
  NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
  NEXT_PUBLIC_APP_SHORT_NAME: process.env.NEXT_PUBLIC_APP_SHORT_NAME,
  NEXT_PUBLIC_APP_DESCRIPTION: process.env.NEXT_PUBLIC_APP_DESCRIPTION,
  NEXT_PUBLIC_APP_VERSION: process.env.NEXT_PUBLIC_APP_VERSION,
  NEXT_PUBLIC_APP_LANGUAGE: process.env.NEXT_PUBLIC_APP_LANGUAGE,
  NEXT_PUBLIC_APP_DIRECTION: process.env.NEXT_PUBLIC_APP_DIRECTION,
  NEXT_PUBLIC_BRAND_LOGO: process.env.NEXT_PUBLIC_BRAND_LOGO,
  NEXT_PUBLIC_BRAND_DARK_LOGO: process.env.NEXT_PUBLIC_BRAND_DARK_LOGO,
  NEXT_PUBLIC_BRAND_MARK: process.env.NEXT_PUBLIC_BRAND_MARK,
  NEXT_PUBLIC_LOGIN_SHOWCASE_TITLE:
    process.env.NEXT_PUBLIC_LOGIN_SHOWCASE_TITLE,
  NEXT_PUBLIC_LOGIN_SHOWCASE_LOGO: process.env.NEXT_PUBLIC_LOGIN_SHOWCASE_LOGO,
  NEXT_PUBLIC_FONT_PRESET: process.env.NEXT_PUBLIC_FONT_PRESET,
  NEXT_PUBLIC_SUPPORT_PHONE: process.env.NEXT_PUBLIC_SUPPORT_PHONE,
  NEXT_PUBLIC_SUPPORT_WHATSAPP: process.env.NEXT_PUBLIC_SUPPORT_WHATSAPP,
  NEXT_PUBLIC_NAV_DASHBOARD: process.env.NEXT_PUBLIC_NAV_DASHBOARD,
  NEXT_PUBLIC_NAV_ACCOUNT: process.env.NEXT_PUBLIC_NAV_ACCOUNT,
  NEXT_PUBLIC_DASHBOARD_MODULE_ARTICLES_LABEL:
    process.env.NEXT_PUBLIC_DASHBOARD_MODULE_ARTICLES_LABEL,
  NEXT_PUBLIC_DASHBOARD_MODULE_LIBRARY_LABEL:
    process.env.NEXT_PUBLIC_DASHBOARD_MODULE_LIBRARY_LABEL,
  NEXT_PUBLIC_DASHBOARD_MODULE_DISSERTATIONS_LABEL:
    process.env.NEXT_PUBLIC_DASHBOARD_MODULE_DISSERTATIONS_LABEL,
  NEXT_PUBLIC_DASHBOARD_MODULE_LISTENING_LABEL:
    process.env.NEXT_PUBLIC_DASHBOARD_MODULE_LISTENING_LABEL,
  NEXT_PUBLIC_DASHBOARD_MODULE_HADITH_CARDS_LABEL:
    process.env.NEXT_PUBLIC_DASHBOARD_MODULE_HADITH_CARDS_LABEL,
  NEXT_PUBLIC_DASHBOARD_MODULE_SCIENTIFIC_FATWAS_LABEL:
    process.env.NEXT_PUBLIC_DASHBOARD_MODULE_SCIENTIFIC_FATWAS_LABEL,
  NEXT_PUBLIC_DASHBOARD_MODULE_SCIENTIFIC_VIDEOS_LABEL:
    process.env.NEXT_PUBLIC_DASHBOARD_MODULE_SCIENTIFIC_VIDEOS_LABEL,
  NEXT_PUBLIC_DASHBOARD_MODULE_LIBRARY_INDEXES_LABEL:
    process.env.NEXT_PUBLIC_DASHBOARD_MODULE_LIBRARY_INDEXES_LABEL,
  NEXT_PUBLIC_DASHBOARD_MODULE_COMMENTS_LABEL:
    process.env.NEXT_PUBLIC_DASHBOARD_MODULE_COMMENTS_LABEL,
  NEXT_PUBLIC_NAV_SECTIONS: process.env.NEXT_PUBLIC_NAV_SECTIONS,
  NEXT_PUBLIC_ENTITY_SECTION_SINGULAR:
    process.env.NEXT_PUBLIC_ENTITY_SECTION_SINGULAR,
  NEXT_PUBLIC_ENTITY_SECTION_PLURAL:
    process.env.NEXT_PUBLIC_ENTITY_SECTION_PLURAL,
  NEXT_PUBLIC_NAV_ARTICLES: process.env.NEXT_PUBLIC_NAV_ARTICLES,
  NEXT_PUBLIC_ENTITY_ARTICLE_SINGULAR:
    process.env.NEXT_PUBLIC_ENTITY_ARTICLE_SINGULAR,
  NEXT_PUBLIC_ENTITY_ARTICLE_PLURAL:
    process.env.NEXT_PUBLIC_ENTITY_ARTICLE_PLURAL,
  NEXT_PUBLIC_NAV_BOOKS: process.env.NEXT_PUBLIC_NAV_BOOKS,
  NEXT_PUBLIC_ENTITY_BOOK_SINGULAR:
    process.env.NEXT_PUBLIC_ENTITY_BOOK_SINGULAR,
  NEXT_PUBLIC_ENTITY_BOOK_PLURAL: process.env.NEXT_PUBLIC_ENTITY_BOOK_PLURAL,
  NEXT_PUBLIC_ENTITY_BOOK_SERIES_SINGULAR:
    process.env.NEXT_PUBLIC_ENTITY_BOOK_SERIES_SINGULAR,
  NEXT_PUBLIC_ENTITY_BOOK_SERIES_PLURAL:
    process.env.NEXT_PUBLIC_ENTITY_BOOK_SERIES_PLURAL,
  NEXT_PUBLIC_NAV_VISUALS: process.env.NEXT_PUBLIC_NAV_VISUALS,
  NEXT_PUBLIC_ENTITY_VISUAL_SINGULAR:
    process.env.NEXT_PUBLIC_ENTITY_VISUAL_SINGULAR,
  NEXT_PUBLIC_ENTITY_VISUAL_PLURAL:
    process.env.NEXT_PUBLIC_ENTITY_VISUAL_PLURAL,
  NEXT_PUBLIC_NAV_GALLERY: process.env.NEXT_PUBLIC_NAV_GALLERY,
  NEXT_PUBLIC_ENTITY_MEDIA_SINGULAR:
    process.env.NEXT_PUBLIC_ENTITY_MEDIA_SINGULAR,
  NEXT_PUBLIC_ENTITY_MEDIA_PLURAL: process.env.NEXT_PUBLIC_ENTITY_MEDIA_PLURAL,
  NEXT_PUBLIC_NAV_SUPERVISORS: process.env.NEXT_PUBLIC_NAV_SUPERVISORS,
  NEXT_PUBLIC_ENTITY_SUPERVISOR_SINGULAR:
    process.env.NEXT_PUBLIC_ENTITY_SUPERVISOR_SINGULAR,
  NEXT_PUBLIC_ENTITY_SUPERVISOR_PLURAL:
    process.env.NEXT_PUBLIC_ENTITY_SUPERVISOR_PLURAL,
  NEXT_PUBLIC_NAV_REPORTS: process.env.NEXT_PUBLIC_NAV_REPORTS,
  NEXT_PUBLIC_ENTITY_REPORT_SINGULAR:
    process.env.NEXT_PUBLIC_ENTITY_REPORT_SINGULAR,
  NEXT_PUBLIC_ENTITY_REPORT_PLURAL:
    process.env.NEXT_PUBLIC_ENTITY_REPORT_PLURAL,
  NEXT_PUBLIC_NAV_SETTINGS: process.env.NEXT_PUBLIC_NAV_SETTINGS,
  NEXT_PUBLIC_ENTITY_SETTING_SINGULAR:
    process.env.NEXT_PUBLIC_ENTITY_SETTING_SINGULAR,
  NEXT_PUBLIC_ENTITY_SETTING_PLURAL:
    process.env.NEXT_PUBLIC_ENTITY_SETTING_PLURAL,
  NEXT_PUBLIC_PAGE_SECTIONS_CREATE_TITLE:
    process.env.NEXT_PUBLIC_PAGE_SECTIONS_CREATE_TITLE,
  NEXT_PUBLIC_PAGE_SECTIONS_EDIT_TITLE:
    process.env.NEXT_PUBLIC_PAGE_SECTIONS_EDIT_TITLE,
  NEXT_PUBLIC_PAGE_SECTIONS_DETAIL_TITLE:
    process.env.NEXT_PUBLIC_PAGE_SECTIONS_DETAIL_TITLE,
  NEXT_PUBLIC_PAGE_ARTICLES_CREATE_TITLE:
    process.env.NEXT_PUBLIC_PAGE_ARTICLES_CREATE_TITLE,
  NEXT_PUBLIC_PAGE_ARTICLES_EDIT_TITLE:
    process.env.NEXT_PUBLIC_PAGE_ARTICLES_EDIT_TITLE,
  NEXT_PUBLIC_PAGE_ARTICLES_DETAIL_TITLE:
    process.env.NEXT_PUBLIC_PAGE_ARTICLES_DETAIL_TITLE,
  NEXT_PUBLIC_PAGE_BOOKS_CREATE_TITLE:
    process.env.NEXT_PUBLIC_PAGE_BOOKS_CREATE_TITLE,
  NEXT_PUBLIC_PAGE_BOOKS_EDIT_TITLE:
    process.env.NEXT_PUBLIC_PAGE_BOOKS_EDIT_TITLE,
  NEXT_PUBLIC_PAGE_BOOKS_DETAIL_TITLE:
    process.env.NEXT_PUBLIC_PAGE_BOOKS_DETAIL_TITLE,
  NEXT_PUBLIC_PAGE_VISUALS_CREATE_TITLE:
    process.env.NEXT_PUBLIC_PAGE_VISUALS_CREATE_TITLE,
  NEXT_PUBLIC_PAGE_VISUALS_EDIT_TITLE:
    process.env.NEXT_PUBLIC_PAGE_VISUALS_EDIT_TITLE,
  NEXT_PUBLIC_PAGE_VISUALS_DETAIL_TITLE:
    process.env.NEXT_PUBLIC_PAGE_VISUALS_DETAIL_TITLE,
  NEXT_PUBLIC_PAGE_GALLERY_CREATE_TITLE:
    process.env.NEXT_PUBLIC_PAGE_GALLERY_CREATE_TITLE,
  NEXT_PUBLIC_PAGE_GALLERY_EDIT_TITLE:
    process.env.NEXT_PUBLIC_PAGE_GALLERY_EDIT_TITLE,
  NEXT_PUBLIC_PAGE_GALLERY_DETAIL_TITLE:
    process.env.NEXT_PUBLIC_PAGE_GALLERY_DETAIL_TITLE,
  NEXT_PUBLIC_PAGE_SUPERVISORS_CREATE_TITLE:
    process.env.NEXT_PUBLIC_PAGE_SUPERVISORS_CREATE_TITLE,
  NEXT_PUBLIC_PAGE_SUPERVISORS_EDIT_TITLE:
    process.env.NEXT_PUBLIC_PAGE_SUPERVISORS_EDIT_TITLE,
  NEXT_PUBLIC_PAGE_SUPERVISORS_DETAIL_TITLE:
    process.env.NEXT_PUBLIC_PAGE_SUPERVISORS_DETAIL_TITLE,
  NEXT_PUBLIC_PAGE_SETTINGS_CREATE_TITLE:
    process.env.NEXT_PUBLIC_PAGE_SETTINGS_CREATE_TITLE,
  NEXT_PUBLIC_PAGE_SETTINGS_EDIT_TITLE:
    process.env.NEXT_PUBLIC_PAGE_SETTINGS_EDIT_TITLE,
  NEXT_PUBLIC_PAGE_SETTINGS_DETAIL_TITLE:
    process.env.NEXT_PUBLIC_PAGE_SETTINGS_DETAIL_TITLE,
});
